npc_quotes = [
    {"name": "Saul D'Alessio", "quote": "And then the Mursaat found me...",
     "avatar": "https://www.dropbox.com/s/ya1sqzt3alomxy0/saul.png?raw=1"},
    {"name": "Crystallographer Smoxxi", "quote": "Let's talk about what's really important - CRYSTALS!",
     "avatar": "https://www.dropbox.com/s/9y9z9uwzz0p34zx/smoxxi.png?raw=1"},
    {"name": "Reaper of the Ice Wastes", "quote": "Dhuum's gaze falls upon me!",
     "avatar": "https://www.dropbox.com/s/cr4o0qkdqe6shwm/reaper.png?raw=1"},
    {"name": "Crusader Aurus Fuseblight", "quote": "Burn me, it's a stingray.",
     "avatar": "https://www.dropbox.com/s/x0kgxetegjsovq6/aurus.png?raw=1"},
    {"name": "Kestrel Zuru", "quote": "This is a place of refuge! Not a...den of iniquity.",
     "avatar": "https://www.dropbox.com/s/nm0w4pkls6m8dnr/kestrel_zuru.png?raw=1"},
    [{"name": "Vigil Crusader", "quote": "Wow! That's quality armor.",
      "avatar": "https://www.dropbox.com/s/mwq2ipe9yrdu9pf/vigil_crusader.png?raw=1", "sleep_after": True},
     {"name": "Vigil Craftsman 1", "quote": "Thanks!",
      "avatar": "https://www.dropbox.com/s/qfukxvjmfp4zt0b/vigil_craftsman_1.png?raw=1"},
     {"name": "Vigil Craftsman 2", "quote": "Thanks!",
      "avatar": "https://www.dropbox.com/s/ir3vnelf2jml54u/vigil_craftsman_2.png?raw=1"},
     {"name": "Vigil Craftsman 3", "quote": "Thanks!",
      "avatar": "https://www.dropbox.com/s/9gw79euni5fmq2l/vigil_craftsman_3.png?raw=1"}],
    {"name": "Asura", "quote": "Six feet tall!",
     "avatar": "https://www.dropbox.com/s/scz9wr6vqepjqqc/gremlin.png?raw=1"},
    {"name": "Lion's Arch Banker", "quote": "More violets I say...less violence.",
     "avatar": "https://www.dropbox.com/s/7d6rjoca31vrt9s/lions_arch_banker.png?raw=1"},
    {"name": "Soulless Horror", "quote": "You dare draw breath in the Realm of the Dead?",
     "avatar": "https://www.dropbox.com/s/p9od3o7oi50m7ae/soulless_horror.png?raw=1"},
    {"name": "Dhuum", "quote": "Breathe your last",
     "avatar": "https://www.dropbox.com/s/jmfo1bo38z3dgss/dhuum.png?raw=1"}
]
